name: Feature Request
description: Suggest an idea for this project
labels: ["type:feature", "status:waiting"]
body:
  - type: markdown
    id: title
    attributes:
      value: |
        Thanks for filling out this feature request!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Please summarize your feature request.
      validations:
        required: true
  - type: textarea
    id: other
    attributes:
      label: Additional Information
      placeholder: Anything else we should know?
      validations:
        required: false