name: Build App

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.idea/**'
      - '.gradle/**'
      - 'gradle/**'
      - 'build/**'
      - 'app/build/**'
      - 'app/src/androidTest/**'
      - 'app/src/test/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.idea/**'
      - '.gradle/**'
      - 'gradle/**'
      - 'build/**'
      - 'app/build/**'
      - 'app/src/androidTest/**'
      - 'app/src/test/**'

jobs:
  build:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
